services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - .:/rails
    ports:
        - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  postgres-data:
    driver: local